Login01
wolox-training/faf-android pull request #1
Opened 2021-07-05 14:28 UTC by FloresFelix

maquetado del login

2021-07-05 14:41 UTC, ffasitella requested changes
I saw you didn't create an activity. Try creating a `LoginActivity` and setting it as the main activity.
I left some comments! Feel free to ask us anything.

2021-07-05 14:41 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/login/LoginFragment.kt
> +                }
This belongs to the card named "Validaciones" 😅 

Also, you should do these validations in the presenter. Remember to never put logic inside the fragment.

2021-07-05 14:41 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/login/LoginFragment.kt
> +class LoginFragment private constructor() : WolmoFragment<FragmentLoginBinding, LoginPresenter>() {
Remember you have to implement the LoginView. 
You can implement classes in kotlin by adding after a comma:
`class LoginFragment : WolmoFragment<FragmentLoginBinding, LoginPresenter>(), LoginView`

2021-07-05 14:41 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/login/LoginView.kt
> +    fun dummyFunction5() {}
Remember to delete these lines after doing the navigation card

2021-07-05 14:41 UTC, ffasitella commented on app/src/main/res/layout/fragment_example.xml
> +			app:layout_constraintHorizontal_bias="1.0"
You don't need this change

2021-07-05 14:41 UTC, ffasitella commented on app/src/main/res/layout/fragment_login.xml
> +            android:layout_marginTop="32dp"
Don't use hardcoded dimens. You can add this dimen inside the `dimens.xml` file to reuse it.

2021-07-05 14:41 UTC, ffasitella commented on app/src/main/res/layout/fragment_login.xml
> +            android:layout_marginEnd="24dp"
Solve hardcoded dimens

2021-07-05 14:41 UTC, ffasitella commented on app/src/main/res/layout/fragment_login.xml
> +            android:layout_marginTop="24dp"
Hardcoded dimen

2021-07-05 14:41 UTC, ffasitella commented on app/src/main/res/layout/fragment_login.xml
> +            android:layout_marginTop="32dp"
Check these hardcoded dimens in the rest of the file

2021-07-05 14:41 UTC, ffasitella commented on app/src/main/res/values/strings.xml
> +    <string name="sing_up">SING UP</string>
Typo, it's `SIGN UP`

2021-07-05 14:41 UTC, ffasitella commented on app/src/main/res/values/strings.xml
> +    <string name="terms"><![CDATA[By joining you agree to our Terms & Conditions]]></string>
You need to make the "Terms & Conditions" part underlined

2021-07-05 15:03 UTC, FloresFelix commented
genail! Voy Revisar!

El lun, 5 jul 2021 a las 11:43, Federico Fasitella (<
***@***.***>) escribió:

> Assigned #1 <https://github.com/wolox-training/faf-android/pull/1> to
> @FloresFelix <https://github.com/FloresFelix>.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wolox-training/faf-android/pull/1#event-4978976505>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQVA6JJFHU2BRSYGE77GNLTWHAJTANCNFSM4722357Q>
> .
>

2021-07-05 16:43 UTC, jcruz-wolox requested changes
I agree with the Fede's comments.
good job, you're doing fine!

2021-07-05 16:43 UTC, jcruz-wolox commented on app/build.gradle
> +
Remove this empty lines

2021-07-05 16:43 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/login/LoginFragment.kt
> +                // Validacion
Comments in English

2021-07-05 16:43 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/login/LoginFragment.kt
> +    fun newInstance() = LoginFragment()
Indent this line

2021-07-05 16:43 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/login/LoginFragment.kt
> +
Remove empty line

2021-07-05 16:43 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/login/LoginPresenter.kt
> +        view?.dummyFunction2()
Don't use numbers like part of names, you should use literals, so, if you going to use dummyFunction2 should rename to dummyFunctionTwo

2021-07-05 16:43 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/login/LoginPresenter.kt
> +    fun onClickTerms() = view?.gotToWeb()
you have a typo in "gotToWeb()" correct with goToWeb()

2021-07-05 16:43 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/login/LoginView.kt
> +    fun dummyFunction2() {}
The same that above with numbers in names

2021-07-05 16:43 UTC, jcruz-wolox commented on app/src/main/res/layout/fragment_login.xml
> +
delete empty line

2021-07-05 17:50 UTC, FloresFelix commented
Quiero que saber mi pueden ayudar en esto... Tengo lleno la bandeja de
entrada de outlook con mensajes que tengo que ir a *myTimeandExpenses and
submit your time as soon possible.* Me pueden dar una breve explicación de
como cargar esos datos, sobre todo en en la pestaña PREFERENCES que es
donde me pide que ponga datos si o si, Gracias

El lun, 5 jul 2021 a las 13:43, Jonatan Cruz Garcia (<
***@***.***>) escribió:

> ***@***.**** requested changes on this pull request.
>
> I agree with the Fede's comments.
> good job, you're doing fine!
> ------------------------------
>
> In app/build.gradle
> <https://github.com/wolox-training/faf-android/pull/1#discussion_r664042074>
> :
>
> > @@ -152,4 +151,7 @@ dependencies {
>
>      // Android KTX
>
>      implementation "androidx.core:core-ktx:$android_ktx_version"
>
>      implementation "androidx.fragment:fragment-ktx:$android_ktx_version"
>
> +
>
>
> Remove this empty lines
> ------------------------------
>
> In
> app/src/main/java/ar/com/wolox/android/example/ui/login/LoginFragment.kt
> <https://github.com/wolox-training/faf-android/pull/1#discussion_r664042594>
> :
>
> > +
>
> +class LoginFragment private constructor() : WolmoFragment<FragmentLoginBinding, LoginPresenter>() {
>
> +
>
> +    override fun layout() = R.layout.fragment_login
>
> +
>
> +    override fun init() {
>
> +    }
>
> +
>
> +    override fun setListeners() {
>
> +        with(binding) {
>
> +
>
> +            editTextEmail.addTextChangedListener {}
>
> +            editTextPassword.addTextChangedListener {}
>
> +            buttonLogin.setOnClickListener {
>
> +
>
> +                // Validacion
>
>
> Comments in English
> ------------------------------
>
> In
> app/src/main/java/ar/com/wolox/android/example/ui/login/LoginFragment.kt
> <https://github.com/wolox-training/faf-android/pull/1#discussion_r664042968>
> :
>
> > +                } else {
>
> +                    if (!android.util.Patterns.EMAIL_ADDRESS.matcher(editTextEmail.text.toString()).matches()) {
>
> +                        editTextEmail.setError("El correo debe tener el formato: ***@***.***")
>
> +                    } else {
>
> +                        presenter.onClickLogin(editTextEmail.text.toString(), editTextPassword.text.toString())
>
> +                    }
>
> +                }
>
> +            }
>
> +            buttonSignup.setOnClickListener { presenter.onClickSingup() }
>
> +            textViewTerms.setOnClickListener { presenter.onClickTerms() }
>
> +        }
>
> +    }
>
> +
>
> +    companion object {
>
> +
>
> +    fun newInstance() = LoginFragment()
>
>
> Indent this line
> ------------------------------
>
> In
> app/src/main/java/ar/com/wolox/android/example/ui/login/LoginFragment.kt
> <https://github.com/wolox-training/faf-android/pull/1#discussion_r664043075>
> :
>
> > +                    editTextPassword.setError("Debe ingresar la contraseña")
>
> +                } else {
>
> +                    if (!android.util.Patterns.EMAIL_ADDRESS.matcher(editTextEmail.text.toString()).matches()) {
>
> +                        editTextEmail.setError("El correo debe tener el formato: ***@***.***")
>
> +                    } else {
>
> +                        presenter.onClickLogin(editTextEmail.text.toString(), editTextPassword.text.toString())
>
> +                    }
>
> +                }
>
> +            }
>
> +            buttonSignup.setOnClickListener { presenter.onClickSingup() }
>
> +            textViewTerms.setOnClickListener { presenter.onClickTerms() }
>
> +        }
>
> +    }
>
> +
>
> +    companion object {
>
> +
>
>
> Remove empty line
> ------------------------------
>
> In
> app/src/main/java/ar/com/wolox/android/example/ui/login/LoginPresenter.kt
> <https://github.com/wolox-training/faf-android/pull/1#discussion_r664045974>
> :
>
> > @@ -0,0 +1,20 @@
>
> +package ar.com.wolox.android.example.ui.login
>
> +
>
> +import ar.com.wolox.wolmo.core.presenter.BasePresenter
>
> +
>
> +class LoginPresenter constructor() : BasePresenter<LoginView>() {
>
> +
>
> +    fun onClickLogin(fistName: String, lastName: String) {
>
> +        view?.dummyFunction()
>
> +    }
>
> +
>
> +    fun onClickSingup() {
>
> +        view?.dummyFunction2()
>
>
> Don't use numbers like part of names, you should use literals, so, if you
> going to use dummyFunction2 should rename to dummyFunctionTwo
> ------------------------------
>
> In
> app/src/main/java/ar/com/wolox/android/example/ui/login/LoginPresenter.kt
> <https://github.com/wolox-training/faf-android/pull/1#discussion_r664046375>
> :
>
> > @@ -0,0 +1,20 @@
>
> +package ar.com.wolox.android.example.ui.login
>
> +
>
> +import ar.com.wolox.wolmo.core.presenter.BasePresenter
>
> +
>
> +class LoginPresenter constructor() : BasePresenter<LoginView>() {
>
> +
>
> +    fun onClickLogin(fistName: String, lastName: String) {
>
> +        view?.dummyFunction()
>
> +    }
>
> +
>
> +    fun onClickSingup() {
>
> +        view?.dummyFunction2()
>
> +    }
>
> +
>
> +    fun onClickTerms() = view?.gotToWeb()
>
>
> you have a typo in "gotToWeb()" correct with goToWeb()
> ------------------------------
>
> In app/src/main/java/ar/com/wolox/android/example/ui/login/LoginView.kt
> <https://github.com/wolox-training/faf-android/pull/1#discussion_r664046678>
> :
>
> > @@ -0,0 +1,16 @@
>
> +package ar.com.wolox.android.example.ui.login
>
> +
>
> +interface LoginView {
>
> +
>
> +    fun dummyFunction() {}
>
> +
>
> +    fun dummyFunction2() {}
>
>
> The same that above with numbers in names
> ------------------------------
>
> In app/src/main/res/layout/fragment_login.xml
> <https://github.com/wolox-training/faf-android/pull/1#discussion_r664046888>
> :
>
> > @@ -0,0 +1,85 @@
>
> +<?xml version="1.0" encoding="utf-8"?>
>
> +
>
> +<layout xmlns:app="http://schemas.android.com/apk/res-auto"
>
> +    xmlns:tools="http://schemas.android.com/tools"
>
> +    xmlns:android="http://schemas.android.com/apk/res/android">
>
> +
>
> +    <androidx.constraintlayout.widget.ConstraintLayout
>
> +        android:layout_width="match_parent"
>
> +        android:layout_height="match_parent"
>
> +        tools:context=".example.ui.login.LoginFragment">
>
> +
>
>
> delete empty line
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wolox-training/faf-android/pull/1#pullrequestreview-699321060>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQVA6M3NPZJ4EFDYG3UE3DTWHOKFANCNFSM4722357Q>
> .
>

2021-07-07 20:29 UTC, ffasitella approved these changes
Good job! 👍🏽

2021-07-07 20:43 UTC, jcruz-wolox approved these changes
Nice!

2021-07-13 13:11 UTC, merged