Navegacion
wolox-training/faf-android pull request #2
Opened 2021-07-12 15:18 UTC by FloresFelix

### Summary
-Navigation:
                  - log in
                  - sign in

### Screenshot

### Trello card
https://trello.com/c/i4mHZmvl

2021-07-12 19:28 UTC, ffasitella requested changes
Some changes to do before merging

2021-07-12 19:28 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/hompage/HomePageFragment.kt
> +        val sharedPref: SharedPreferences? = activity?.getSharedPreferences(R.string.prefs_name.toString(), Context.MODE_PRIVATE)
you can get the prefs_name with `context.getString(R.string.prefs_name)`

2021-07-12 19:28 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/login/LoginFragment.kt
> +            sharedPref.edit().putBoolean(R.string.state.toString(), true).apply()
same here

2021-07-12 19:28 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/login/LoginFragment.kt
> +        val sharedPref: SharedPreferences? = activity?.getSharedPreferences(R.string.prefs_name.toString(), Context.MODE_PRIVATE)
same here

2021-07-12 19:28 UTC, ffasitella commented on app/src/main/res/values/strings.xml
> +    <string name="state">state</string>
what's this?

2021-07-13 18:46 UTC, ffasitella approved these changes
👍🏽

2021-07-13 18:53 UTC, FloresFelix commented
Genial, hasta el momento estoy entendiendo bien el backend login del
ejemplo. Solo una cosa, no puedo identificar en que clase hace la
conexión con el servidor a la api, (por ejemplo donde iria
https://w-android-training.herokuapp.com/ para hacer la peticiones)

El mar, 13 jul 2021 a las 15:46, Federico Fasitella (<
***@***.***>) escribió:

> ***@***.**** approved this pull request.
>
> 👍🏽
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wolox-training/faf-android/pull/2#pullrequestreview-705532697>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQVA6LYX5BLHZZKFIZTE5TTXSCZRANCNFSM5AHB627Q>
> .
>

2021-07-16 13:09 UTC, merged