Implementacion del card Home page: Frontend - News
wolox-training/faf-android pull request #7
Opened 2021-07-29 17:59 UTC by FloresFelix

Summary
implementación del card Home page: Frontend - News

Screenshot

Trello card
https://trello.com/c/xXBJJpOl

2021-07-29 19:41 UTC, ffasitella requested changes
Left some comments. Check this PR, it has some merge conflicts. You shoul merge master to this branch to solve them.
Also, add a screenshot to show how this looks 👀

2021-07-29 19:41 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/model/ItemNewsModel.kt
> +)
You will need to change this names when you perform the integration with backend.

2021-07-29 19:41 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsAdapter.kt
> +        holder.newsLike.setImageResource(listNews[position].newsLike)
`holder.apply {} `

2021-07-29 19:41 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsAdapter.kt
> +        val time = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").parse(listNews[position].newsTime).time
move the date format to a constant

2021-07-29 19:41 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsFragment.kt
> +    }
`with(binding)`

2021-07-29 19:41 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsPresenter.kt
> +            if (num % 2 == 0) {
Why do you need this? 🤔

2021-07-29 19:41 UTC, ffasitella commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsPresenter.kt
> +        view?.loadRecyclerView(list)
You should do this in an if/else statement. `if (list.isEmpty) showEmptyNews else showNews`

2021-07-29 20:03 UTC, jcruz-wolox requested changes
Hello Félix!! 

I have any comments.

One suggestion, you can make comments from here (Github PR), i think that you is making comments by responding the github notifications emails, shouldn't response them because it generates spam in the PR.

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsAdapter.kt
> +class NewsAdapter constructor(var context: Context, var listNews: ArrayList<ItemNewsModel>) : RecyclerView.Adapter<NewsAdapter.NewsViewHolder>() {
Never forget run the "Code -> Reformat Code" Android Studio tool to make sure that your code is well indented.

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsFragment.kt
> +            presenter.refreshNews()
Rename this presenter function to onSwipeRefresh(), remember that the fragment notify to presenter asking what should I do? Usually, the fragment don't take decision by itself.

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsFragment.kt
> +        binding.newsRecyclerView.layoutManager = LinearLayoutManager(requireContext())
Use "with" function like I mentioned above. If don't understand ask us, no problem.

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsFragment.kt
> +        binding.imageViewEmptyNews.visibility = View.VISIBLE
Same as above

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsFragment.kt
> +        presenter.setListNews()
You should rename this presenter function to onInit and make private the setListNews function, so, call setListnews function from onInit. Remember, the fragment allways ask what should make?

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsPresenter.kt
> +        view?.loadRecyclerView(list)
Rename this function to any more descriptive, the presenter don't know about Recycler Views. You could rename to loadNewsList.

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/res/drawable/ic_add.xml
> +    android:width="24dp"
Move to dimens.xml file the width and height values.

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/res/drawable/ic_favorite.xml
> +    android:width="24dp"
Same as above, move to dimens.xml width and height values.

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/res/drawable/ic_favorite_border.xml
> +    android:width="24dp"
Same as above.

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/res/drawable/ic_news_icons.xml
> +    android:width="24dp"
Same as above.

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/res/layout/fragment_news.xml
> +
Remove empty lines.

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsPresenter.kt
> +    fun refreshNews() {
You could rename to onRefreshNews and call setListNews() function

2021-07-29 20:03 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsFragment.kt
> +        presenter.setListNews()
Call to onRefreshNews() function. Below I explain how

2021-07-30 13:24 UTC, FloresFelix commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsFragment.kt
> +        presenter.setListNews()
sorry I don't understand...

2021-07-30 14:12 UTC, jcruz-wolox commented on app/src/main/java/ar/com/wolox/android/example/ui/viewpager/news/NewsFragment.kt
> +        presenter.setListNews()
Sorry, I confused you. The idea is that you convert to private setListNews and create onInit function to call it here. Example:

NewsFragment.kt

`override fun init() {
    presenter.onInit()
}`

-------------------------------

Presenter:

`// New function called onInit()
fun onInit() {
    setListNews()
}`

`// the setListNews function converted to private. you'll be able to call this function also when you refresh the news list
private fun setListNews() {
 
}`

2021-08-02 12:34 UTC, ffasitella approved these changes
Good job! In a real project, you will fight merge conflicts very often. Well done 👍🏽 
Let's wait for Jona's approval!

2021-08-02 12:49 UTC, jcruz-wolox approved these changes

2021-08-02 15:34 UTC, merged